# Generated by Django 3.0.4 on 2020-04-29 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_Category',
            fields=[
                ('ingredient_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Category')),
                ('ingredient', models.ManyToManyField(to='HeyFoodie.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='Ingredient_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Ingredient_Category'),
        ),
    ]
