# Generated by Django 3.0.4 on 2020-04-29 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_Category',
            fields=[
                ('ingredient_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Category')),
                ('ingredient', models.ManyToManyField(to='HeyFoodie.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('order_status', models.CharField(max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=10)),
                ('bankacc_no', models.CharField(max_length=10)),
                ('bankname', models.CharField(max_length=5)),
                ('promptpay', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User_Rating',
            fields=[
                ('user_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Customer')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('storename', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=255)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('open_day', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'MON'), (2, 'TUE'), (3, 'WED'), (4, 'THU'), (5, 'FRI'), (6, 'SAT'), (7, 'SUN')], max_length=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Customer')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Month',
            fields=[
                ('report_month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=3)),
                ('monthly_sale', models.DecimalField(decimal_places=2, max_digits=7)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Day',
            fields=[
                ('report_day_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('daily_sale', models.DecimalField(decimal_places=2, max_digits=7)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('purchase_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Order')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='Ingredient_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Ingredient_Category'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Customer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Bestsellmenu_Month',
            fields=[
                ('bestsell_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
                ('report_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Report_Month')),
            ],
        ),
        migrations.CreateModel(
            name='Bestsellmenu_Day',
            fields=[
                ('bestsell_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
                ('report_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Report_Day')),
            ],
        ),
    ]
