# Generated by Django 3.0.4 on 2020-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient_category',
            name='ingredient_category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
