# Generated by Django 3.0.4 on 2020-04-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
