# Generated by Django 3.0.4 on 2020-05-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0002_auto_20200429_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='order_detail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('COOKING', 'Cooking'), ('READYTOPICKUP', 'Ready To Pickup'), ('DONE', 'Done')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
