# Generated by Django 3.0.4 on 2020-05-10 22:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HeyFoodie', '0002_auto_20200429_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('order_status', models.CharField(choices=[('WAITING', 'Waiting'), ('COOKING', 'Cooking'), ('READYTOPICKUP', 'Ready To Pickup'), ('DONE', 'Done')], default='WAITING', max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Day',
            fields=[
                ('report_day_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('daily_sale', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Month',
            fields=[
                ('report_month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=3)),
                ('monthly_sale', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('storename', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=255)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('open_day', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'MON'), (2, 'TUE'), (3, 'WED'), (4, 'THU'), (5, 'FRI'), (6, 'SAT'), (7, 'SUN')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='User_Rating',
            fields=[
                ('user_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Customer')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Customer')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('purchase_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ManyToManyField(to='HeyFoodie.Ingredient')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Order')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Customer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Bestsellmenu_Month',
            fields=[
                ('bestsell_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
                ('report_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Report_Month')),
            ],
        ),
        migrations.CreateModel(
            name='Bestsellmenu_Day',
            fields=[
                ('bestsell_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
                ('report_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Report_Day')),
            ],
        ),
    ]
