# Generated by Django 3.0.4 on 2020-08-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0004_auto_20200512_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.CreateModel(
            name='SaleSize',
            fields=[
                ('salesize_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Menu')),
            ],
        ),
    ]
