# Generated by Django 3.0.4 on 2020-04-21 17:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0005_auto_20200421_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='store_id',
            new_name='store',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeyFoodie.Image'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='owner',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
