# Generated by Django 3.0.4 on 2020-04-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0008_auto_20200422_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Image'),
        ),
    ]
